# Generated by Django 5.1.3 on 2024-11-09 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('cpu_percent', models.FloatField()),
                ('ram_total', models.IntegerField()),
                ('ram_available', models.IntegerField()),
                ('ram_used', models.IntegerField()),
                ('host_id', models.CharField(max_length=255)),
                ('os', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('platform_version', models.CharField(max_length=255)),
                ('processes', models.IntegerField()),
            ],
        ),
    ]
