# Generated by Django 5.1.3 on 2024-12-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
