services:
  server:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    networks:
      - local
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles
    command: uvicorn config.wsgi --bind 0.0.0.0:8000 --workers 1

  rpc:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    networks:
      - local
    ports:
      - "8091:50051"
    env_file:
      - .env
    command: uv run manage.py grpcrunaioserver

  nginx:
    image: nginx:latest
    depends_on:
      - server
    ports:
      - "80:80"
    volumes:
      - ./docker/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - staticfiles:/staticfiles
    networks:
      - local

volumes:
  staticfiles:

networks:
  local:
    driver: bridge 
